export const  BOOKING_CREATE_REQUEST = ' BOOKING_CREATE_REQUEST';
export const  BOOKING_CREATE_SUCCESS = ' BOOKING_CREATE_SUCCESS';
export const  BOOKING_CREATE_FAILURE = ' BOOKING_CREATE_FAILURE';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAILURE = 'BOOKING_DETAILS_FAILURE';

export const BOOKING_PAY_REQUEST = 'BOOKING_PAY_REQUEST';
export const BOOKING_PAY_SUCCESS = 'BOOKING_PAY_SUCCESS';
export const BOOKING_PAY_FAILURE = 'BOOKING_PAY_FAILURE';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const BOOKING_DELIVER_REQUEST = 'BOOKING_DELIVER_REQUEST';
export const BOOKING_DELIVER_SUCCESS = 'BOOKING_DELIVER_SUCCESS';
export const BOOKING_DELIVER_FAILURE = 'BOOKING_DELIVER_FAILURE';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const BOOKING_USER_LIST_REQUEST = 'BOOKING_USER_LIST_REQUEST';
export const BOOKING_USER_LIST_SUCCESS = 'BOOKING_USER_LIST_SUCCESS';
export const BOOKING_USER_LIST_FAILURE = 'BOOKING_USER_LIST_FAILURE';
export const ORDER_USER_LIST_RESET = 'ORDER_USER_LIST_RESET';

export const BOOKING_ALL_LIST_REQUEST = 'BOOKING_ALL_LIST_REQUEST';
export const BOOKING_ALL_LIST_SUCCESS = 'BOOKING_ALL_LIST_SUCCESS';
export const BOOKING_ALL_LIST_FAILURE = 'BOOKING_ALL_LIST_FAILURE';
