export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAILURE = 'MOVIE_DETAILS_FAILURE';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';

export const MOVIE_CREATE_REQUEST = 'MOVIE_CREATE_REQUEST';
export const MOVIE_CREATE_SUCCESS = 'MOVIE_CREATE_SUCCESS';
export const MOVIE_CREATE_FAILURE = 'MOVIE_CREATE_FAILURE';
export const MOVIE_CREATE_RESET = 'MOVIE_CREATE_RESET';

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_UPDATE_FAILURE = 'MOVIE_UPDATE_FAILURE';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';

export const PRODUCT_TOP_RATED_REQUEST = 'PRODUCT_TOP_RATED_REQUEST';
export const PRODUCT_TOP_RATED_SUCCESS = 'PRODUCT_TOP_RATED_SUCCESS';
export const PRODUCT_TOP_RATED_FAILURE = 'PRODUCT_TOP_RATED_FAILURE';
